#!/bin/bash

# Automatically added from template:

dpkg -L python3-jsonpickle | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'

# End automatically added section